# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
