# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0002_auto_20180127_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='chosen_category',
            field=models.CharField(blank=True, choices=[(None, 'Выберите категорию'), ('Пенсионеры и Инвалиды', 'Пенсионеры и Инвалиды'), ('Малоимущие семьи', 'Малоимущие семьи'), ('Больные дети и сироты', 'Больные дети и сироты'), ('Храмы и монастыри', 'Храмы и монастыри'), ('Заключеные', 'Заключенные'), ('Дома милосердия', 'Дома милосердия')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='chosen_category_2',
            field=models.CharField(blank=True, choices=[(None, 'Выберите категорию'), ('Материальная', 'Материальная'), ('Нематериальная', 'Нематериальная')], default=None, max_length=100, null=True),
        ),
    ]
