# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0003_auto_20180127_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='logo_pic',
            field=models.ImageField(blank=True, height_field=400, null=True, upload_to='static/img/', width_field=400),
        ),
    ]
