# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0004_create_logo_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
