# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0005_auto_20180127_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='logo_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
