# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitemira', '0006_auto_20180128_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='create',
            name='coordinates',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='create',
            name='low_description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='create',
            name='name_project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
