# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0007_auto_20180128_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='organizathion_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='chosen_category',
            field=models.CharField(choices=[(None, 'Выберите категорию'), ('Пенсионеры и Инвалиды', 'Пенсионеры и Инвалиды'), ('Малоимущие семьи', 'Малоимущие семьи'), ('Больные дети и сироты', 'Больные дети и сироты'), ('Храмы и монастыри', 'Храмы и монастыри'), ('Заключеные', 'Заключенные'), ('Дома милосердия', 'Дома милосердия')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='chosen_category_2',
            field=models.CharField(choices=[(None, 'Выберите категорию'), ('Материальная', 'Материальная'), ('Нематериальная', 'Нематериальная')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='coordinates',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='logo_pic',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='create',
            name='name_project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='create',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
