# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0008_auto_20180128_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='name_project',
            field=models.CharField(max_length=100, null=True, verbose_name='Название проекта'),
        ),
    ]
