# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 08:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitemira', '0012_auto_20180131_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200, null=True)),
                ('blog_text', models.TextField(null=True)),
                ('blog_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('blog_items', models.FileField(null=True, upload_to='media/%Y/%m/%d')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
