# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-21 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemira', '0013_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sitemira.blog'),
        ),
    ]
